// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

package com.meta.pixelandtexel.geovoyage.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF316A3D)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFB2F0B8)
val onPrimaryContainerLight = Color(0xFF423F47)
val secondaryLight = Color(0xFF4D644F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD1EBD0)
val onSecondaryContainerLight = Color(0xFF384E3A)
val tertiaryLight = Color(0xFF006972)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF96EFFB)
val onTertiaryContainerLight = Color(0xFF004F57)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF8FAF3)
val onBackgroundLight = Color(0xFF191C19)
val surfaceLight = Color(0xFFF8FAF3)
val onSurfaceLight = Color(0xFF191C19)
val surfaceVariantLight = Color(0xFFDCE5D9)
val onSurfaceVariantLight = Color(0xFF414940)
val outlineLight = Color(0xFF71796F)
val outlineVariantLight = Color(0xFFC0C9BD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E312D)
val inverseOnSurfaceLight = Color(0xFFEFF2EB)
val inversePrimaryLight = Color(0xFF98D59F)
val surfaceDimLight = Color(0xFFD8DBD4)
val surfaceBrightLight = Color(0xFFF8FAF3)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F4EE)
val surfaceContainerLight = Color(0xFFECEFE8)
val surfaceContainerHighLight = Color(0xFFE7E9E2)
val surfaceContainerHighestLight = Color(0xFFE1E3DD)

val primaryDark = Color(0xFFFFFFFF)
val onPrimaryDark = Color(0xFF003916)
val primaryContainerDark = Color(0xFFA5E3AC)
val onPrimaryContainerDark = Color(0xFF0C4921)
val secondaryDark = Color(0xFFB4CDB3)
val onSecondaryDark = Color(0xFF203523)
val secondaryContainerDark = Color(0xFF2C422F)
val onSecondaryContainerDark = Color(0xFFBED7BD)
val tertiaryDark = Color(0xFFFFFFFF)
val onTertiaryDark = Color(0xFF00363C)
val tertiaryContainerDark = Color(0xFF89E2EE)
val onTertiaryContainerDark = Color(0xFF00474D)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111411)
val onBackgroundDark = Color(0xFFE1E3DD)
val surfaceDark = Color(0xFF111411)
val onSurfaceDark = Color(0xFFE1E3DD)
val surfaceVariantDark = Color(0xFF414940)
val onSurfaceVariantDark = Color(0xFFC0C9BD)
val outlineDark = Color(0xFF8B9389)
val outlineVariantDark = Color(0xFF414940)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E3DD)
val inverseOnSurfaceDark = Color(0xFF2E312D)
val inversePrimaryDark = Color(0xFF316A3D)
val surfaceDimDark = Color(0xFF111411)
val surfaceBrightDark = Color(0xFF373A36)
val surfaceContainerLowestDark = Color(0xFF0C0F0C)
val surfaceContainerLowDark = Color(0xFF191C19)
val surfaceContainerDark = Color(0xFF1D201D)
val surfaceContainerHighDark = Color(0xFF272B27)
val surfaceContainerHighestDark = Color(0xFF323631)

val customColorLight = Color(0xFF3C6185)
val onCustomColorLight = Color(0xFFFFFFFF)
val customColorContainerLight = Color(0xFFB6D8FF)
val onCustomColorContainerLight = Color(0xFF1A4264)

val customColorDark = Color(0xFFEFF5FF)
val onCustomColorDark = Color(0xFF023354)
val customColorContainerDark = Color(0xFFA8CDF6)
val onCustomColorContainerDark = Color(0xFF103B5C)
